version: "3.3"

services:
  jboss.keycloak:
    build: .
#    image: jboss/keycloak:14.0.0
    image: gunnaraccso/keycloak.server:14.0.0
    restart: always
    environment:
      TZ: Europe/Berlin
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak1!
    ports:
      - "9001:8443"
      - "9000:8080"